# Generated by Django 5.2.6 on 2026-09-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
