# Generated by Django 5.2.6 on 2026-09-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceps', '0002_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='estados/'),
        ),
    ]
