# Generated by Django 5.2.6 on 2026-09-27 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceps', '0004_alter_estado_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='nome',
        ),
    ]
